version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: hazeevpn-frontend:latest
    container_name: hazeevpn-web
    restart: unless-stopped
    # Используем expose вместо ports, чтобы порт был доступен
    # только внутри сети Docker для Nginx, но не из интернета
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - hazeenet

  nginx:
    image: nginx:alpine
    container_name: hazeevpn-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Сразу открываем порт для будущего SSL (HTTPS)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt   # Папка с сертификатами
      - ./certbot/www:/var/www/certbot    # Папка для проверки владения доменом
    depends_on:
      - web
    networks:
      - hazeenet

networks:
  hazeenet:
    driver: bridge