services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: hazeevpn-frontend:latest
    container_name: hazeevpn-web
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - hazeenet

  nginx:
    image: nginx:alpine
    container_name: hazeevpn-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    networks:
      - hazeenet

  certbot:
    image: certbot/certbot
    container_name: hazeevpn-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  hazeenet:
    driver: bridge