import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { TelegramProvider } from "@/lib/telegram-provider";
import Script from "next/script";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${montserrat.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
        <link rel="prefetch" href="/cl.html" />
      </head>
      <body className="min-h-full flex flex-col">
          <TelegramProvider>
            {children}
          </TelegramProvider>
      </body>
    </html>
  );
}

