import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          {children}
          <Toaster
              position="top-center"
              toastOptions={{
                  duration: 2000,
                  style: {
                      background: '#18181b',
                      color: '#fff',
                      borderRadius: '16px',
                      border: '1px solid #27272a',
                      fontSize: '14px',
                      fontWeight: 500,
                  },
              }}
          />
      </body>
    </html>
  );
}
