server {
    listen 80;
    server_name webapp.hazeevpn.com;
    server_tokens off;

    # Специальный путь, куда Certbot положит проверочный файл
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Все остальные запросы пока редиректим на HTTPS (которого еще нет)
    location / {
        return 301 https://$host$request_uri;
    }
}